import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'

// Generate AI recommendation for an issue using the AI service
export async function POST(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  try {
    // Fetch the issue
    const issue = await db.issue.findUnique({
      where: { id: params.id },
      include: {
        recommendations: true
      }
    })

    if (!issue) {
      return NextResponse.json(
        { error: 'Issue not found' },
        { status: 404 }
      )
    }

    // Check if we already have recent recommendations (within last hour)
    const recentRecommendation = issue.recommendations.find(
      rec => Date.now() - new Date(rec.createdAt).getTime() < 60 * 60 * 1000
    )

    if (recentRecommendation) {
      return NextResponse.json({
        message: 'Recent recommendation already exists',
        recommendation: recentRecommendation
      })
    }

    // Fetch similar issues from the database
    const similarIssues = await db.issue.findMany({
      where: {
        status: 'RESOLVED',
        OR: [
          { category: issue.category || undefined },
          { priority: issue.priority }
        ],
        NOT: { id: issue.id }
      },
      take: 5,
      orderBy: {
        resolvedAt: 'desc'
      }
    })

    // Call AI service for recommendations
    try {
      const aiServiceResponse = await fetch('http://localhost:3001/api/recommendations?XTransformPort=3001', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          issueTitle: issue.title,
          issueDescription: issue.description,
          symptoms: issue.symptoms,
          category: issue.category,
          similarIssues: similarIssues.map(i => ({
            id: i.id,
            title: i.title,
            resolution: i.resolution
          }))
        })
      })

      if (!aiServiceResponse.ok) {
        throw new Error('AI service request failed')
      }

      const aiData = await aiServiceResponse.json()

      // Store the recommendation in the database
      const recommendation = await db.aIRecommendation.create({
        data: {
          issueId: issue.id,
          recommendation: aiData.recommendation,
          confidence: aiData.confidence,
          reasoning: aiData.reasoning,
          context: aiData.context ? JSON.stringify(aiData.context) : null,
          accepted: null
        }
      })

      // Generate and store embeddings for RAG
      const embeddingText = `Issue: ${issue.title}\nDescription: ${issue.description}\nSymptoms: ${issue.symptoms || ''}\nCategory: ${issue.category || ''}`
      
      try {
        await fetch('http://localhost:3002/api/vectors?XTransformPort=3002', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            id: `issue-${issue.id}`,
            content: embeddingText,
            vector: [], // Will be generated by RAG service
            type: 'issue',
            sourceId: issue.id,
            metadata: {
              category: issue.category,
              priority: issue.priority
            }
          })
        })
      } catch (ragError) {
        console.error('Failed to store embedding:', ragError)
        // Don't fail the recommendation if embedding fails
      }

      return NextResponse.json({
        success: true,
        recommendation
      })
    } catch (aiError) {
      console.error('AI service error:', aiError)
      
      // Create a basic recommendation as fallback
      const fallbackRecommendation = await db.aIRecommendation.create({
        data: {
          issueId: issue.id,
          recommendation: `Based on the issue "${issue.title}", I recommend investigating the following areas:\n\n1. Check system logs for errors\n2. Review recent changes to the affected components\n3. Verify if similar issues have occurred before\n\nFor detailed analysis, please ensure the AI service is running.`,
          confidence: 0.5,
          reasoning: 'AI service unavailable - using fallback template',
          context: null,
          accepted: null
        }
      })

      return NextResponse.json({
        success: true,
        recommendation: fallbackRecommendation,
        warning: 'AI service unavailable - using fallback recommendation'
      })
    }
  } catch (error) {
    console.error('Failed to generate AI recommendation:', error)
    return NextResponse.json(
      { error: 'Failed to generate recommendation' },
      { status: 500 }
    )
  }
}
